"""Add free-text address fields to shipments

Revision ID: d5ccf4c33e30
Revises: c4ff577685a2
Create Date: 2025-07-08 12:30:30.770154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ccf4c33e30'
down_revision: Union[str, None] = 'c4ff577685a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('delivery_address_text', sa.Text(), nullable=True))
    op.drop_constraint(op.f('shipments_recipient_id_fkey'), 'shipments', type_='foreignkey')
    op.drop_constraint(op.f('shipments_delivery_address_id_fkey'), 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'delivery_address_id')
    op.drop_column('shipments', 'recipient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('shipments', sa.Column('delivery_address_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('shipments_delivery_address_id_fkey'), 'shipments', 'addresses', ['delivery_address_id'], ['id'])
    op.create_foreign_key(op.f('shipments_recipient_id_fkey'), 'shipments', 'users', ['recipient_id'], ['id'])
    op.drop_column('shipments', 'delivery_address_text')
    # ### end Alembic commands ###
